item {
    id: 1
    name: 'Box'
}

item {
    id: 2
    name: 'Cone'
}

item {
    id: 3
    name: 'TrackLine'
}

item {
    id: 4
    name: 'Zebra'
}

item {
    id: 5
    name: 'GreenL'
}


item {
    id: 6
    name: 'BlueL'
}


item {
    id: 7
    name: 'SpeedBump'
}

